### ISSUE TITLE
Action scheduler: pre-execute function

### ISSUE THREAD

**Issue by espitall** [cocobot/libcocobot#7]

**Comment by espitall** [comment]
En réfléchissant, je me dit qu'il faudrait aussi une action cleanup exécuté à la fin même si ça a raté.

Par exemple, on veut prendre un coquillage:
- tu exectues pre-execute -> j'ouvre la meca pour prendre un palet
- tu lances le pathfinder
- un tombe sur un adversaire
- on recalcule une stratégie
- on ne pousse plus le coquillage, mais on part à la peche
- j'ai toujours la méca pour palet ouverte, mais c'est incompatible avec la peche.

**Comment by shazame** [comment]
Ça me semble pertinent en effet ! Je me dis que ma blague de "matrice de
fonctions callback" n'est plus si loin de la réalité xD
Heureusement que tu envoies cette réflexion maintenant, j'étais justement
sur le point d'ajouter la fonction "pre-execute".

**Comment by espitall** [comment]
Juste à temps :)

Le 29 mars 2016 à 17:50, David Bitonneau notifications@github.com a écrit
:

> Ça me semble pertinent en effet ! Je me dis que ma blague de "matrice de
> fonctions callback" n'est plus si loin de la réalité xD
> Heureusement que tu envoies cette réflexion maintenant, j'étais justement
> sur le point d'ajouter la fonction "pre-execute".
>

**Comment by shazame** [comment]
Avant d'implémenter ça trop rapidement, j'ajoute un void \* callback_arg par
nouvelle callback (un pour le cleanup et un pour le preexec) ou alors je ne
laisse qu'un seul callback_arg générique qui sera appelé avec chacune des
différentes callback et c'est l'utilisateur qui paramètre son arg et ses
fonctions suivant son usage ?
Je dois partir donc je pusherai le code plus tard en fonction de ta réponse.

**Comment by espitall** [comment]
Le même ça me va :)

Le 29 mars 2016 à 18:10, David Bitonneau notifications@github.com a écrit
:

> Avant d'implémenter ça trop rapidement, j'ajoute un void \* callback_arg par
> nouvelle callback (un pour le cleanup et un pour le preexec) ou alors je ne
> laisse qu'un seul callback_arg générique qui sera appelé avec chacune des
> différentes callback et c'est l'utilisateur qui paramètre son arg et ses
> fonctions suivant son usage ?
> Je dois partir donc je pusherai le code plus tard en fonction de ta
> réponse.
>

**Comment by shazame** [comment]
Je préfère aussi, le prototype de la fonction est déjà bien assez long :p
